name: data-pipeline-workflow

on:
  schedule:
    - cron: "30 0 * * *" # run every day at 12:35 AM
  workflow_dispatch:  # manual triggers

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the python file
        run: python streamlit_app.py # run data pipeline
