[theme]
# primaryColor = '#900C3F' # Bright Orange
# backgroundColor = '#C70039' # Dark Blue
# secondaryBackgroundColor = '#900C3F' # Lighter Blue
# textColor="#FCF5ED"
# font="sans serif"

primaryColor="#6DB9EF"
backgroundColor="#6DB9EF"
secondaryBackgroundColor="#3081D0"
textColor="#262730"
font="sans serif"


