[theme]
primaryColor = '#55B2FF' # Bright Orange
backgroundColor = '#00325B' # Dark Blue
secondaryBackgroundColor = '#55B2FF' # Lighter Blue
textColor="#ffffff"
font="sans serif"

# primaryColor="#6eb52f"
# backgroundColor="#f0f0f5"
# secondaryBackgroundColor="#e0e0ef"
# textColor="#262730"
# font="sans serif"


